services:
  # --- Application Services ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/job_queue?sslmode=disable
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET_NAME=resumes
    depends_on:
      - db
      - redis
      - minio
      - createbuckets

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./worker
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/turbo_eureka?sslmode=disable
      - REDIS_URL=redis:6379
      - VALKEY_PASSWORD=
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET_NAME=resumes
    depends_on:
      - db
      - redis
      - minio

  # --- Infrastructure Services ---
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: turbo_eureka
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Auto-runs your SQL migration
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

  # Utility container to create the bucket automatically
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minioadmin minioadmin; do echo '...waiting for minio'; sleep 1; done;
      mc mb local/resumes --ignore-existing;
      exit 0;
      "

volumes:
  postgres_data:
  redis_data:
  minio_data:
